### PR TITLE
Fix #1037

### LINKED ISSUE #1037: Lazarus 1.8.0 support
Hi all

As new version of lazarus released recently, do you plan to update sources for support it?
I've mad some dirty hacks in code  and transgui compiles successfully under 1.8.0rcX even with Qt5-frontend. But I am not sure if my workarounds acceptable. If you mind I can publish my "patches".

### PR DESCRIPTION
**Pull request by spleenjack**
Added Lazarus 1.8 support
Fixed BaseForm.ScaleD variable name conflicted with Form.Scaled
Fixed usages of some FileUtil deprecated functions

### CODE REVIEW

**Comment by spleenjack** [comment]
I'll squash and rebase if necessary whne build get green (still waiting macos) and these fixes are suitable all in all.

**Comment by sardanap** [comment]
compiles ok on high sierra 10.13.2

**Comment by PeterDaveHello** [comment]
@spleenjack would you please squash the commits? Thanks.

**Comment by PeterDaveHello** [comment]
For code-level changes, I think we need review from @leonsoft-kras and @antekgla

**Comment by spleenjack** [comment]
I fixed that kind of errors:

> baseform.pas(120,20) Error: Incompatible types: got "Boolean" expected "Int64"
baseform.pas(121,40) Error: Incompatible type for arg no. 2: Got "Boolean", expected "LongInt"
baseform.pas(240,6) Error: Incompatible types: got "Boolean" expected "Int64"
baseform.pas(241,13) Error: Incompatible type for arg no. 1: Got "ShortInt", expected "Boolean"
baseform.pas(251,17) Error: Incompatible type for arg no. 1: Got "ShortInt", expected "Boolean"
baseform.pas(254,15) Error: Incompatible types: got "Boolean" expected "LongInt"
baseform.pas(259,17) Error: Operator is not overloaded: "Boolean" * "ShortInt"
utils.pas(177,22) Error: Identifier not found "ParamStrUTF8"
utils.pas(308,6) Error: Identifier not found "FileExistsUTF8"
utils.pas(328,6) Error: Identifier not found "FileExistsUTF8"
utils.pas(333,74) Error: Identifier not found "SysErrorMessageUTF8"
restranslator.pas(156,6) Error: Identifier not found "FindFirstUTF8"
restranslator.pas(169,13) Error: Identifier not found "FindNextUTF8"
restranslator.pas(248,6) Error: Identifier not found "ExtractFileNameOnly"
restranslator.pas(246,3) Error: Identifier not found "LCLGetLanguageIDs"

Snipped piece of code from FileUtil:
```
{$IFDEF EnableWrapperFunctions}
// *** Wrappers for LazUTF8 ***
function ParamStrUTF8(Param: Integer): string; inline; deprecated 'Use the function in LazUTF8 unit';
function SysErrorMessageUTF8(ErrorCode: Integer): String; inline; deprecated 'Use the function in LazUTF8 unit';
[...]
// *** Wrappers for LazFileUtils ***
function ExtractFileNameOnly(const AFilename: string): string; inline; deprecated 'Use the function in LazFileUtils unit';
function FileExistsUTF8(const Filename: string): boolean; inline; deprecated 'Use the function in LazFileUtils unit';
function FindFirstUTF8(const Path: string; Attr: Longint; out Rslt: TSearchRec): Longint; inline; deprecated 'Use the function in LazFileUtils unit';
function FindNextUTF8(var Rslt: TSearchRec): Longint; inline; deprecated 'Use the function in LazFileUtils unit';
{$ENDIF EnableWrapperFunctions}
```

And the little piece from LCLProc:
```
{$IFDEF EnableWrapperFunctions}
  procedure LCLGetLanguageIDs(var Lang, FallbackLang: String); inline; deprecated 'Use function LazGetLanguageIDs in LazUTF8 unit';
{$ENDIF EnableWrapperFunctions}
```

**Comment by spleenjack** [comment]
Squashed and rebased

**Comment by PeterDaveHello** [comment]
I'll also test it soon, in the meantime, let's wait for two another maintainer's review 👍

**Comment by antekgla** [comment]
I test soon too.
I am learning how to have two different Lazarus Versions (1.6 & 1.8) installed in the same machine, and dont screw up his configs.
In a few days I think I would compile this in 1.8

**Comment by PeterDaveHello** [comment]
@antekgla you can try Docker, let me know if I can help you :)

**Comment by antekgla** [comment]
Well I compile this code without problems in Lazarus 1.6 **and** Lazarus 1.8 in **Windows 7**.
The only difference is what exe file is 286 KB bigger now (after Strip)

**Comment by PeterDaveHello** [comment]
@spleenjack would you please tell me the platform(s) you tested with this patch?

**Comment by spleenjack** [comment]
@PeterDaveHello Windows 10. I compiled it on Lazarus 1.6.2, 1.6.4, and 1.8.0 successfully.

**Comment by PeterDaveHello** [comment]
@spleenjack cool! I'll also test it on Windows 7 and Windows 10.
I'm a little bit busy right now, will test it soon, Linux platforms won't be a problem, but I'll need someone to help test it on macOS.

**Comment by PeterDaveHello** [comment]
@leonsoft-kras don't we need more tests?

**Comment by leonsoft-kras** [comment]
Tests are performed all the time. )))

Lazarus 1.6.4 compiled normally. The program works. I did not find the crime in the corrections.

Releases can be compiled in any version of Lazarus.
Users can run the previous version of the program if necessary.

**Comment by PeterDaveHello** [comment]
I prefer to test on all platforms before merging.

**Comment by leonsoft-kras** [comment]
I do not have such an opportunity. In addition, as I have seen above, much has already been tested. so everything is fine.

**Comment by PeterDaveHello** [comment]
just don't think it's in urgent so prefer to have more time to test as detail as possible :)
